"use client";
import { useEffect, useMemo, useState } from 'react';
import { Bell, Clock3, RefreshCw, Search } from 'lucide-react';
import type { Deal, DealsResponse, HistoryResponse, PriceHistoryItem, RedditCategoriesResponse } from '@/lib/types';
import { normalizeText } from '@/lib/text';

function cls(...v: string[]) { return v.filter(Boolean).join(' '); }
function Badge({ children }: { children: React.ReactNode }) { return <span className="inline-flex items-center rounded-full bg-slate-100 px-3 py-1 text-xs font-medium text-slate-700">{children}</span>; }
function Card({ children, className = '' }: { children: React.ReactNode; className?: string }) { return <div className={cls('rounded-[24px] border border-slate-200 bg-white shadow-sm', className)}>{children}</div>; }
function badgeByScore(score: number) { if (score >= 90) return 'Excelente'; if (score >= 80) return 'Muy buena'; if (score >= 70) return 'Buena'; return 'Media'; }
export default function HomePage() {
  const [deals, setDeals] = useState<Deal[]>([]);
  const [history, setHistory] = useState<PriceHistoryItem[]>([]);
  const [categories, setCategories] = useState<Record<string, string[]>>({});
  const [selectedCategory, setSelectedCategory] = useState('deals');
  const [loading, setLoading] = useState(true);
  const [refreshing, setRefreshing] = useState(false);
  const [updatedAt, setUpdatedAt] = useState('');
  const [query, setQuery] = useState('pokemon');
  const [message, setMessage] = useState('');
  useEffect(() => { loadAll(); loadCategories(); }, []);
  async function loadCategories() { const r = await fetch('/api/reddit/categories', { cache: 'no-store' }); const d: RedditCategoriesResponse = await r.json(); setCategories(d.categories ?? {}); setSelectedCategory(d.defaultCategory ?? 'deals'); }
  async function loadAll() { try { setLoading(true); const [dr, hr] = await Promise.all([fetch('/api/deals', { cache: 'no-store' }), fetch('/api/history', { cache: 'no-store' })]); const dd: DealsResponse = await dr.json(); const hd: HistoryResponse = await hr.json(); setDeals(dd.deals ?? []); setHistory(hd.items ?? []); setUpdatedAt(dd.updatedAt ?? ''); } finally { setLoading(false); } }
  async function triggerRefresh() { setRefreshing(true); try { const r = await fetch('/api/refresh', { method:'POST', headers:{ 'content-type':'application/json' }, body: JSON.stringify({ category: selectedCategory }) }); const d = await r.json(); setMessage(d.message ?? ''); await loadAll(); } finally { setRefreshing(false); } }
  const filteredDeals = useMemo(() => deals.filter((deal) => normalizeText(`${deal.title} ${deal.setName}`).includes(normalizeText(query))), [deals, query]);
  const topDeal = [...filteredDeals].sort((a,b) => b.score - a.score)[0];
  return <main className="min-h-screen bg-slate-50 p-4 text-slate-900 md:p-8"><div className="mx-auto max-w-7xl space-y-6">
    <Card className="overflow-hidden bg-gradient-to-r from-white to-slate-100 p-6 md:p-8"><div className="grid gap-6 md:grid-cols-3">
      <div className="space-y-4 md:col-span-2"><div className="text-sm text-slate-600">Fase 6: Reddit por categorías + fallback automático</div><h1 className="text-3xl font-semibold tracking-tight md:text-5xl">Pokemon Deals Radar</h1><p className="max-w-2xl text-base text-slate-600 md:text-lg">El refresh consulta Reddit por categoría y subreddits configurados. Si no encuentra deals con precio parseable, usa fallback dummy.</p><div className="flex flex-wrap gap-2"><Badge>Reddit API</Badge><Badge>Categorías</Badge><Badge>price_history</Badge></div><div className="text-sm text-slate-500">{updatedAt ? `Última actualización: ${new Date(updatedAt).toLocaleString('es-ES')}` : 'Cargando...'}</div>{message ? <div className="rounded-2xl border border-slate-200 bg-white px-4 py-3 text-sm text-slate-600">{message}</div> : null}</div>
      <Card className="p-5"><div className="mb-1 text-sm text-slate-500">Mejor oferta detectada</div><div className="mb-4 text-xs text-slate-400">Ranking por score y precio por sobre</div>{loading ? <div className="text-slate-500">Cargando ofertas...</div> : topDeal ? <div className="space-y-3"><div className="text-sm text-slate-500">{topDeal.source}</div><div className="text-xl font-semibold leading-snug">{topDeal.title}</div><div className="flex items-center justify-between"><span className="text-3xl font-bold">€{topDeal.price.toFixed(2)}</span><Badge>{badgeByScore(topDeal.score)}</Badge></div><div className="text-sm text-slate-600">€{topDeal.pricePerPack.toFixed(2)} por sobre</div></div> : <div className="text-slate-500">No hay resultados.</div>}</Card>
    </div></Card>
    <div className="grid gap-6 lg:grid-cols-4"><Card className="p-5 lg:col-span-1"><div className="mb-4 text-lg font-semibold">Filtros y fuente</div><div className="space-y-4"><div><label className="mb-2 block text-sm font-medium">Buscar</label><div className="relative"><Search className="absolute left-3 top-3 h-4 w-4 text-slate-400" /><input value={query} onChange={(e) => setQuery(e.target.value)} className="w-full rounded-2xl border border-slate-200 bg-white py-3 pl-10 pr-4 outline-none placeholder:text-slate-400 focus:border-slate-400" placeholder="151, ETB, booster..." /></div></div><div><label className="mb-2 block text-sm font-medium">Categoría Reddit</label><select value={selectedCategory} onChange={(e) => setSelectedCategory(e.target.value)} className="w-full rounded-2xl border border-slate-200 bg-white px-4 py-3 outline-none focus:border-slate-400">{Object.keys(categories).length === 0 ? <option value="deals">deals</option> : Object.keys(categories).map((c) => <option key={c} value={c}>{c}</option>)}</select><div className="mt-2 text-xs text-slate-500">{(categories[selectedCategory] ?? []).join(', ')}</div></div><button onClick={triggerRefresh} disabled={refreshing} className="inline-flex w-full items-center justify-center gap-2 rounded-2xl bg-slate-900 px-4 py-3 text-sm font-medium text-white hover:bg-slate-800 disabled:opacity-60"><Bell className="h-4 w-4" />{refreshing ? 'Actualizando...' : 'Actualizar fuente Reddit'}</button></div></Card>
    <div className="space-y-6 lg:col-span-3"><div className="flex items-center gap-2"><button onClick={loadAll} disabled={loading} className="inline-flex items-center gap-2 rounded-2xl border border-slate-200 bg-white px-4 py-2 text-sm font-medium hover:bg-slate-50 disabled:opacity-60"><RefreshCw className={cls('h-4 w-4', loading ? 'animate-spin' : '')} />Recargar API</button></div><div className="grid gap-4 md:grid-cols-2 xl:grid-cols-3">{loading ? <Card className="p-5 md:col-span-2 xl:col-span-3"><div className="text-slate-500">Cargando ofertas...</div></Card> : filteredDeals.map((deal) => <Card key={deal.id} className="p-5"><div className="mb-4 flex items-start justify-between gap-3"><Badge>{deal.source}</Badge><Badge>{deal.score}/100</Badge></div><div className="mb-2 text-lg font-semibold leading-snug">{deal.title}</div><div className="mb-4 text-sm text-slate-500">{deal.setName} · {deal.productType}</div><div className="mb-4 grid grid-cols-2 gap-3"><div className="rounded-2xl bg-slate-100 p-3"><div className="text-xs text-slate-500">Precio</div><div className="text-lg font-semibold">€{deal.price.toFixed(2)}</div></div><div className="rounded-2xl bg-slate-100 p-3"><div className="text-xs text-slate-500">€/sobre</div><div className="text-lg font-semibold">€{deal.pricePerPack.toFixed(2)}</div></div></div><div className="mb-4 flex flex-wrap gap-2 text-sm text-slate-600"><span className="inline-flex items-center gap-1">{deal.seller}</span><span className="inline-flex items-center gap-1">{badgeByScore(deal.score)}</span></div><div className="text-xs text-slate-500">{deal.status}</div></Card>)}</div>
    <div className="grid gap-4">{history.length === 0 ? <Card className="p-5"><div className="text-slate-500">Aún no hay snapshots. Pulsa Actualizar fuente Reddit.</div></Card> : history.slice(0, 10).map((item) => <Card key={item.id} className="p-5"><div className="flex flex-col gap-3 md:flex-row md:items-center md:justify-between"><div><div className="text-lg font-semibold">{item.title}</div><div className="mt-1 flex items-center gap-2 text-sm text-slate-500"><Clock3 className="h-4 w-4" />{new Date(item.observedAt).toLocaleString('es-ES')}</div></div><div className="grid grid-cols-2 gap-3 md:w-[260px]"><div className="rounded-2xl bg-slate-100 p-3"><div className="text-xs text-slate-500">Precio</div><div className="text-lg font-semibold">€{item.price.toFixed(2)}</div></div><div className="rounded-2xl bg-slate-100 p-3"><div className="text-xs text-slate-500">€/sobre</div><div className="text-lg font-semibold">€{item.pricePerPack.toFixed(2)}</div></div></div></div></Card>)}</div>
    </div></div></div></main>;
}
